### ISSUE TITLE
"View Details"-Button not working properly [Firefox]

### ISSUE THREAD

**Issue by xilef6000** [checkmyhttps/checkmyhttps#1]
Heyho dear developers,
The "View Details"-Button is not redirecting to the Information about the actual open page.

#### First one
Steps to reproduce:
Open new browser window, (for me the default page is about:home), klick the yellow lock symbol of CheckMyHTTPS, then klick on "View Details"

Actual result:
https://checkmyhttps.net/addon.php?url=**https://checkmyhttps.net**[...] opens.

Expected result:
Button should have been grayed out,
or should inform the user that the addon does not work for internal pages.

#### Second one
Steps to reproduce:
Browse to https://google.com (or *ANY* other website) and klick the Lock Symbol (mostly green [**also not working!**]) and then on "View Details"

Actual result:
https://checkmyhttps.net/addon.php?url=https://checkmyhttps.net[...] opens.

Expected result:
Actual result:
https://checkmyhttps.net/addon.php?url=$DOMAIN&thumbprint=$DOMAINTHUMBPRINT&thumbprint_256=$DOMAINTHUMBPRINT256 opens.

#### Third one
it's getting better with every point ^^
The reason, why I installed this plugin: to know when i am the victim of an MITM attack.

Steps to reproduce:
Do a MITM attack on a computer. (With fake ssl certificate)
On this computer, open firefox with installed plugin and browse to a https encrypted website

Actual result:
The lock rests yellow, even if the browser warns me of the unsecure connection.

Expected result:
Lock turns red.

If i accept the security exception, (or the certificate is trusted), i manually have to click on the "View Details" button before anything happens to the lock color

**Comment by checkmyhttps** [comment]
Hello,

Thanks for your feedback :)
We have just launched a more stable and faster addon.

### The first one
It has been fixed.

### The second one
The second problem has been fixed ...but if you test the addon when you are consulting a big website like  "https://www.google.fr", the fingerprint seen by the server and seen by the client will be different because it (=big websites) uses several SSL certificate ... it's embarrassing because for the moment we have no idea about how to fix this problem.

### The Third one
You need to accept the self-signed certificate to make addon works. Firefox API allow you to check the current accepted certificate, it could be useful if the IT team of company upload the company CA certificate on all the equipments because we could detect an SSL inspection (red lock).

It will not work if the URL is an IP (for example : https://192.168.1.10), we are working on it.

Best regards and thanks again,
checkmyhttps
