### ISSUE TITLE
'Check when the page loads' option not working 

### ISSUE THREAD

**Issue by Cade66** [checkmyhttps/checkmyhttps#20]
_CheckMyHTTPS_ 5.5.1 / Firefox 78.0.2 (x64)

Hi,

I just tried the _Check when the page loads_ option and it is not working. After HTTPS page is loaded icon is unchanged, message remains _Click to verify this HTTPS connection_ and, once clicked, delivers analysis as usual.
I'm posting this without being sure if this is an issue on my browser only (given possible conflicts) or if it is a native _CheckMyHTTPS 5.5.1_ issue.

Thanks for letting me know if you encounter this.

**Comment by QuentinClrt** [comment]
Hello,

Thank you for reporting this cons. The project leader will then pay me a beer ! We have fixed the current problem and will publish it on Mozilla soon.

CheckMyHTTPS Team

**Comment by Cade66** [comment]
Why are you closing this thread given,
1- if it's an issue then other users may be interested to know it's in the waiting list;
2- if it's an issue it isn't resolved, only transmitted;
2- is it an issue? I was expecting a confirmation. Can other users confirm or infirm my first comment? If I'm the only one to experience the issue then it isn't an issue, then no point in transmitting.

Sorry to be so check-list driven but sometimes I just don't understand the protocol on some GitHub repositories.

**Comment by QuentinClrt** [comment]
We've tried to reduce permissions using the "activeTabs" permission by the generic "tabs" permission into the manifest.json file. Meanwhile, this option can not let us an access to the current tab and the 'Check when the page loads' option does not work as you told us. The corrected version comes soon.

Please, reefer to the last commits to see the detailed answer. The problem is now fixed so we decided to close this thread.

We are sorry for the disagreement. Have a nice day!

**Comment by rexy74** [comment]
The 5.5.2 version of CMH has just been published with the fix of your bug report. Thx @Cade66 & @QuentinClrt

**Comment by Cade66** [comment]
CMH 5.5.2 available, issue fixed, acknowledged.
I should have had a look on _last commits_, I'm a simple user not yet aware of GitHub and up to now I'd refer only to the basic issue pages.
Thanks.
