### ISSUE TITLE
Compatibility with Firefox Quantum

### ISSUE THREAD

**Issue by maximang** [checkmyhttps/checkmyhttps#5]
Hi,

Is it possible to make the extension compatible with Firefox Quantum?

Thanks!

**Comment by Tom-H-** [comment]
Hello,

Since Firefox 57, only WebExtensions are allowed. However, the TLS API is not implemented yet. So we cannot access to the certificate information.
You can follow the [Bug 1322748](https://bugzilla.mozilla.org/show_bug.cgi?id=1322748) on the Mozilla BugTracker and the draft [EFForg/webrequest-tlsinfo-api](https://github.com/EFForg/webrequest-tlsinfo-api/blob/master/proposal.md).

In the meantime, we have planned to release a WebExtension version with Native messaging and a Python script (maybe in a month, maybe more...). This solution has several disadvantages (more complex installation, can't verify the original browser request), but it may allow compatibility with other browsers (such as Chrome).

**Comment by Tom-H-** [comment]
Hello,

Our WebExtension version has just been accepted by Mozilla and is available on https://addons.mozilla.org/firefox/addon/checkmyhttps/ (commit d42532f144714eca5da825807084608452ca9754).
It should also be available on Google Chrome and Opera soon.
