### ISSUE TITLE
Une fois OK, une fois KO

### ISSUE THREAD

**Issue by nitrique** [checkmyhttps/checkmyhttps#7]
Bonjour,

J'ai essayé le script python avec l'adresse https://nitrique.fr, il retourne une fois OK, une fois KO, une fois OK, une fois KO.
Est-ce dû à let's encrypt ?

Merci.
Nicolas

--

Hey guys,

When I try with this url : https://nitrique.fr, the cert check return one time OK, one time Ko, one time OK....
Is that related to let's encrypt ?

Thanks,
Nicolas

**Comment by Tom-H-** [comment]
Hello,

The problem is not Let's Encrypt but seems to be rather your load balancer/router (Træfik). It uses several SSL certificates (apparently 4) for the domain `nitrique.fr`.
The use of multiple certificates collides with the design of CheckMyHTTPS. If your HTTPS server does not use the same certificate with the client and the check server, CheckMyHTTPS cannot ensure the security of the communication.

**Comment by rexy74** [comment]
The "python" script (native-app/checkmyhttps.py) is no more used since FF56. We will probably delete it in a future version of CMH.
