### ISSUE TITLE
So many permissions

### ISSUE THREAD

**Issue by gronono** [checkmyhttps/checkmyhttps#8]
Hello,

I have not tested your extension yet but that's exactly what I need.
However, before installing it I don't see why this extension needs so many permissions. I get the following list of https://addons.mozilla.org/en/firefox/addon/checkmyhttps/

* "Access your data for all websites": you can read the pages viewed and worse the data entered (such as passwords).
* "Exchange messages with programs other than Firefox": you can call programs on my machine. I do not see why you need to do that.
* "Download files and read and modify the browser’s download history": I guess you need it to check the certificate on download URLs?
* "Display notifications to you": no worries with this one
* "Access browser tabs": I think it allows you to recover the url so no worries either.

The description of this extension is very well done but could you complete it to make it clear why you need these permissions?
And could you remove "Exchange messages with programs other than Firefox" and "Access your data for all websites" ?

Thank you in advance for your response.
Regards.

**Comment by Tom-H-** [comment]
Hello,

I will try to explain to you the relevance of each permission:

| Permission | Description |
| --- | --- |
| "Access your data for all websites" | this is used to get the event of URL change (to refresh icon status or check at page load option), only tab id, URL and origin URL are used (not body content) |
| "Exchange messages with programs other than Firefox" | it's currently necessary in order to call our Python script (it will no longer be necessary in the future version using the new TLS API) |
| "Download files and read and modify the browser’s download history" | just used in the settings page to download our Python script |
| "Display notifications to you" | to show notifications |
| "Access browser tabs" | manipulate tabs (ex: on tab switch, refresh icon status of the current tab) |

So all these permissions seem currently necessary :)

Thank you for your interest in the CheckMyHTTPS project.

**Comment by gronono** [comment]
Thanks a lot. I'll test it tomorrow at work.

**Comment by Gitoffthelawn** [comment]
Thank you for CheckMyHTTPS.  Can the Python script now be removed to remove two of the permissions?

Also, can you add the above information to the extension's official listing on AMO?

**Comment by rexy74** [comment]
Yes you are right. We can remove the python script. We will try to do that during the end of this year.
Stay tune

**Comment by checkmyhttps** [comment]
Good evening,

Indeed, you can delete the python script to save data if you have a recent browser version. A new one will be released in the next months to decrease all the permission due to the python script and then, increase the privacy.

We take note of your request.

Regards,
CheckMyHTTPS Team.


________________________________
De : Gitoffthelawn <notifications@github.com>
Envoyé : jeudi 12 décembre 2019 22:03:32
À : checkmyhttps/checkmyhttps <checkmyhttps@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [checkmyhttps/checkmyhttps] So many permissions (#8)


Thank you for CheckMyHTTPS. Can the Python script now be removed to remove two of the permissions?

Also, can you add the above information to the extension's official listing on AMO?

**Comment by rexy74** [comment]
@Checkmyhttps = Quentin | Catarina | Tom ?

**Comment by rexy74** [comment]
In the last version of CMH (5.5), we have removed the python script made by Tom for old versions of Firefox (<= V65). Right now, we need only 3 permissions : "access your data for all websites", "Display notifications to you" & "Access browser tabs".
We are looking for decrease this one : "access your data for all websites".

**Comment by Gitoffthelawn** [comment]
Is it best to keep this issue open or closed since work is still in progress to remove the "Access your data for all websites" permission?

**Comment by rexy74** [comment]
You are right. I think we will not be able to totally remove this permission, but replace it with an other one that is less permissive.

**Comment by rexy74** [comment]
We reduce again permissions in the next version : https://github.com/checkmyhttps/checkmyhttps/commit/4d96f3f795f1534ab36f0bb1dfd59a6d755a89c1
